parameters:
  name: build
  vmImage: ubuntu-latest
  variables: {}
  allowFailure: false
  __osname:
    ubuntu-16.04: linux
    ubuntu-latest: linux
    macos-10.13: macos10.13
    macos-10.14: macos10.14
    macos-latest: macos
  __isLinux:
    ubuntu-16.04: 'True'
    ubuntu-latest: 'True'

jobs:
- job: ${{parameters.name}}
  displayName: ${{parameters.__osname[parameters.vmImage]}}/${{coalesce(parameters.variables.NIX_CHANNELS_NIXPKGS, '$(NIX_CHANNELS_NIXPKGS)')}}
  timeoutInMinutes: 0
  pool:
    vmImage: ${{parameters.vmImage}}
  variables:
    ${{insert}}: ${{parameters.variables}}
    TERM: linux
    GITHUB_TOKEN: $(github.token.empty)
  continueOnError: ${{ eq(parameters.allowFailure, 'true') }}
  steps:
  - checkout: self
    submodules: true
  - template: azure/nix/install.yml@ci
    parameters:
      ciVersion: allnix
      config: ci/config.nix
  - template: azure/nix/test.yml@ci
    parameters:
      ciVersion: allnix
      config: ci/config.nix
      timeoutInMinutes: 240 # max: 360
