parameters:
  name: build
  displayName: Build
  # intended only as reusable variables
  imageMacos: macos-latest

stages:
- stage: ${{parameters.name}}
  displayName: ${{parameters.displayName}}
  jobs:
  - template: job.yml
    parameters:
      name: pending_pr
      variables:
        NIX_CHANNELS_NIXPKGS: pending-pr
  - template: job.yml
    parameters:
      name: macos_pending_pr
      vmImage: ${{parameters.imageMacos}}
      variables:
        NIX_CHANNELS_NIXPKGS: pending-pr
