parameters:
  name: build
  displayName: Build
  # intended only as reusable variables
  imageMacos: macos-latest

stages:
- stage: ${{parameters.name}}
  displayName: ${{parameters.displayName}}
  jobs:
  - template: job.yml
    parameters:
      name: stable
      variables:
        NIX_CHANNELS_NIXPKGS: "19.03"
        NIX_CHANNELS_HOME_MANAGER: release-19.03
  - template: job.yml
    parameters:
      name: macos_stable
      vmImage: ${{parameters.imageMacos}}
      variables:
        NIX_CHANNELS_NIXPKGS: "19.03"
        NIX_CHANNELS_HOME_MANAGER: release-19.03
      allowFailure: true
  - template: job.yml
    parameters:
      name: unstable
      variables:
        NIX_CHANNELS_NIXPKGS: unstable
  - template: job.yml
    parameters:
      name: unstable_small
      variables:
        NIX_CHANNELS_NIXPKGS: unstable-small
      allowFailure: true
  - template: job.yml
    parameters:
      name: nixpkgs_unstable
      variables:
        NIX_CHANNELS_NIXPKGS: nixpkgs-unstable
      allowFailure: true
  - template: job.yml
    parameters:
      name: macos_unstable
      vmImage: ${{parameters.imageMacos}}
      variables:
        NIX_CHANNELS_NIXPKGS: unstable
      allowFailure: true
